version: '3.4'

services:

  go-backend:
    build: ./backend
    container_name: go-backend
    # environment:
    #   - DB_SERVER=kanban-postgres
    #   - POSTGRES_DB=kanban
    #   - POSTGRES_USER=kanban
    #   - POSTGRES_PASSWORD=kanban
    ports:
      - 8080:8080
  
  react-ui:
    build: ./the-ui
    container_name: react-ui
    ports:
      - 4200:80
    links:
      - react-app


volumes:
  kanban-data:



# services:
#   webapp:
#     ports:
#       - "9000:8080"
#     volumes:
#       - ".:/usr/src/app"
#     build:
#       context: .
#       network: host