version: '3.4'

services:
  # networks: host

  #sqlite database needs to be mounted(?) into this container, TODO: read up & understand volume mounting and binding
  go-backend:
    build: ./backend
    container_name: go-backend
    # volumes:
    #   - data-vol:/data
    environment:
      - HOST=127.0.0.1
      - PORT=8080
      - DB_CONN="./do.db"
    ports:
      - 8080:8080
    # networks:
    #   - host
  
#   react-ui:
#     build: ./the-ui
#     container_name: react-ui
#     ports:
#       - 4200:80
#     links:
#       - react-app

# volumes:
#   data-vol:



# services:
#   webapp:
#     ports:
#       - "9000:8080"
#     volumes:
#       - ".:/usr/src/app"
#     build:
#       context: .
#       network: host

# Volumes are stored in a part of the host filesystem which is managed by Docker (/var/lib/docker/volumes/ on Linux). 
# Non-Docker processes should not modify this part of the filesystem. Volumes are the best way to persist data in Docker.

# Bind mounts may be stored anywhere on the host system. They may even be important system files or directories. 
# Non-Docker processes on the Docker host or a Docker container can modify them at any time.